version: "3.5"

services:
    web:
        build: deps/
        restart: on-failure
        ports:
            - "8000:8000"
        volumes:
            - "./deps/:/usr/src/deps_app/"
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        depends_on:
            - db
    
    db:
        image: postgres:12.0
        volumes:
            - pgs_data:/var/lib/postgresql/data/
        env_file:
            - ./deps/envs/.env.dev.db.docker
volumes:
    pgs_data:
